import {useEffect,useRef} from 'react';
import type { PlayerView } from '../../shared/eclipse/types';
import { usePublicInspection } from './PublicInspectionContext';
import { historyPresentationLines, historySectorIds, scoreInspection } from './publicInspection';
import GalaxyBoard from './GalaxyBoard';
export default function PublicInspectionModal({view}:{view:PlayerView}){
 const inspection=usePublicInspection(),panel=useRef<HTMLElement>(null),active=inspection?.active;
 useEffect(()=>{if(!active)return;const prior=document.activeElement instanceof HTMLElement?document.activeElement:null;panel.current?.focus();return()=>prior?.focus();},[active]);
 if(!active)return null;
 const ids=active.kind==='history'?historySectorIds(active.entry):scoreInspection(view,active.seatId,active.category).sectorIds;
 const detail=active.kind==='score'?scoreInspection(view,active.seatId,active.category):null,presentation=active.kind==='history'?historyPresentationLines(active.entry):[];
 const currentIds=ids.filter(id=>view.sectors.some(sector=>sector.id===id)),missing=ids.filter(id=>!currentIds.includes(id));
 const keyDown=(event:React.KeyboardEvent<HTMLElement>)=>{if(event.key==='Escape'){event.stopPropagation();inspection?.dismiss();return;}if(event.key!=='Tab')return;const focusable=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],summary')??[]);if(!focusable.length){event.preventDefault();return;}const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};
 return <section ref={panel} tabIndex={-1} onKeyDown={keyDown} className="dg-public-inspection" role="dialog" aria-modal="true" aria-label={active.kind==='history'?'Public history inspection':'Public score inspection'}><header><h2>{active.kind==='history'?active.entry.summary:`${detail!.title} · ${detail!.value} VP`}</h2><button onClick={inspection?.dismiss}>Close</button></header><p>{active.kind==='history'?'Historical references use public action metadata. Ships and control may have changed since this action.':detail!.explanation}</p>{presentation.length>0&&<p className="dg-history-presentation">{presentation.join(' · ')}</p>}{detail?.contributors.length? <ul>{detail.contributors.map(contributor=><li key={contributor}>{contributor}</li>)}</ul>:null}{currentIds.length>0&&<div className="dg-public-inspection-map"><GalaxyBoard initialFit view={view} candidates={[]} selected={null} legalTargetIds={currentIds} targetLabel="public contributor sector" onSelect={()=>{}} onExplore={()=>{}}/></div>}{missing.length>0&&<p role="status">Referenced historical sector{missing.length===1?' is':'s are'} no longer on the current public board.</p>}{!currentIds.length&&ids.length===0&&<p>This public action has no spatial reference to highlight.</p>}<p>Highlights and ships use the current public board; historical pieces may have moved.</p></section>;
}
