import {advanceCombat,resolveCombatChoice} from '../../shared/eclipse/battleEngine';
import {createGame} from '../../shared/eclipse/setup';
import {randomSeed} from '../../shared/eclipse/random';
import type {GameState} from '../../shared/eclipse/types';

/** Isolated review setup. The saved roll itself is generated by the authoritative engine. */
export function riftCombatReviewFixture():GameState {
  const state=createGame({seed:932,warpPortals:true,riftCannons:true,seats:[{id:'rift',faction:'eridani',controller:'human'},{id:'shield',faction:'hydran',controller:'human'}]});
  const attacker=state.seats[0],defender=state.seats[1];
  attacker.blueprints.find(blueprint=>blueprint.shipType==='interceptor')!.parts=['rift-cannon','fusion-source','nuclear-drive','electron-computer'];
  defender.blueprints.find(blueprint=>blueprint.shipType==='dreadnought')!.parts=['ion-cannon','fusion-source','nuclear-drive','phase-shield','improved-hull',null,null,null];
  const sectorId=state.ships.find(ship=>ship.owner==='shield')!.sectorId;
  state.ships=[{id:'rift-interceptor',owner:'rift',type:'interceptor',sectorId,damage:0,arrival:2},{id:'shield-dreadnought',owner:'shield',type:'dreadnought',sectorId,damage:0,arrival:1}];
  state.phase='combat';state.activeSeatId=null;state.seats.forEach(seat=>{seat.passed=true;});
  advanceCombat(state,[]);
  const turn=state.pendingDecision;
  if(turn?.kind!=='combat-turn')throw new Error('Rift fixture must begin with a combat turn.');
  // mulberry32-v1 seed 3 begins with face 5: three damage and one backfire.
  state.random=randomSeed(3);
  resolveCombatChoice(state,turn.owner,turn,{kind:'combat-turn',retreatTo:null},[]);
  return state;
}
