import {DiscoveryRewardStats} from './DiscoveryDecision';
import {useState} from 'react';
import type {GameCommand,PendingDecision,ScifiProject} from '../../shared/eclipse/types';
import {DISCOVERIES} from '../../shared/eclipse/discoveries';
import {TECHNOLOGIES} from '../../shared/eclipse/technologies';
import {SHIP_PARTS,isShipPartId} from '../../shared/eclipse/parts';
import TechnologyStats from './TechnologyStats';
import ShipPartStats from './ShipPartStats';
type Decision=Extract<PendingDecision,{kind:'discovery-draft'|'technology-reservation'|'reverse-engineering'}>;
export default function ScifiDecision({decision,disabled,onSubmit}:{decision:Decision;disabled:boolean;onSubmit:(command:GameCommand)=>void}){
 const [selected,setSelected]=useState<number[]>([]);
 const [project,setProject]=useState<ScifiProject|null>(null);
 const [reservation,setReservation]=useState<string|null>(null);
 if(decision.kind==='discovery-draft')return <section className="dg-decision"><p className="sd-eyebrow">SKIPPY'S CACHES · PRIVATE CHOICE</p><h2>Choose {decision.keepCount} discoveries</h2><p>Each selected tile then uses the normal discovery choices. Unselected tiles return to the supply.</p><div className="sd-tech-grid">{decision.tileIds.map((id,index)=>{const tile=DISCOVERIES.find(t=>t.id===id);return <label key={`${id}-${index}`}><input type="checkbox" checked={selected.includes(index)} disabled={disabled||(!selected.includes(index)&&selected.length>=decision.keepCount)} onChange={()=>setSelected(values=>values.includes(index)?values.filter(v=>v!==index):[...values,index])}/><strong>{tile?.name??id}</strong><small>{tile?.effect.kind.replaceAll('-',' ')}</small>{tile&&<DiscoveryRewardStats effect={tile.effect} faction="exfor"/>}</label>;})}</div><button className="sd-primary" disabled={disabled||selected.length!==decision.keepCount} onClick={()=>onSubmit({type:'resolve',decisionId:decision.id,choice:{kind:'discovery-draft',tileIds:selected.map(index=>decision.tileIds[index])}})}>Keep {decision.keepCount} discoveries</button></section>;
 if(decision.kind==='technology-reservation')return <section className="dg-decision"><h2>Reserve a technology</h2><p>One market copy is yours alone until your next turn or round end. Reverse engineering remains available.</p><div className="sd-tech-grid">{decision.tileIds.map((id,index)=>{const tech=TECHNOLOGIES.find(t=>t.id===id);return <button key={`${id}-${index}`} disabled={disabled} aria-pressed={reservation===id} onClick={()=>setReservation(id)}><strong>{tech?.name??id}</strong>{tech&&<TechnologyStats technology={tech}/>}</button>;})}</div><button disabled={disabled||!reservation} onClick={()=>onSubmit({type:'resolve',decisionId:decision.id,choice:{kind:'technology-reservation',tileId:reservation}})}>Confirm reservation</button><button disabled={disabled} onClick={()=>onSubmit({type:'resolve',decisionId:decision.id,choice:{kind:'technology-reservation',tileId:null}})}>Skip reservation</button></section>;
 return <section className="dg-decision"><h2>Record a reverse-engineering project</h2><p>Choose one observed technology or Ancient part. Completing it later consumes a Research activation and Science. Only one project can be held.</p><div className="sd-tech-grid">{decision.projects.map(item=>{const tech=item.kind==='technology'?TECHNOLOGIES.find(t=>t.id===item.id):null;return <button key={`${item.kind}-${item.id}`} disabled={disabled} aria-pressed={project?.kind===item.kind&&project.id===item.id} onClick={()=>setProject(item)}><strong>{tech?.name??(item.kind==='ancient-part'?SHIP_PARTS.find(t=>t.id===item.id)?.name:item.id)??item.id}</strong>{tech?<TechnologyStats technology={tech}/>:isShipPartId(item.id)?<ShipPartStats partId={item.id}/>:null}</button>;})}</div><button disabled={disabled||!project} onClick={()=>onSubmit({type:'resolve',decisionId:decision.id,choice:{kind:'reverse-engineering',project}})}>Record project</button><button disabled={disabled} onClick={()=>onSubmit({type:'resolve',decisionId:decision.id,choice:{kind:'reverse-engineering',project:null}})}>Skip project</button></section>;
}
