// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import type {GameCommand} from '../../shared/eclipse/types';
import type {PublicHistoryEntry} from '../../shared/eclipse/history';
import {DiceRollScopeContext} from '../second-dawn-game/presentationSettings';
import {useGameSoundFeedback,type SoundFeedbackOptions} from '../second-dawn-game/sound/useGameSoundFeedback';
const audio=vi.hoisted(()=>({play:vi.fn(),stop:vi.fn()}));
vi.mock('../second-dawn-game/sound/runtime',()=>({playCosmeticCue:audio.play,stopCosmeticCues:audio.stop}));
let testScope=0;
const move:GameCommand={type:'move',moves:[{shipId:'one',path:['a','b']},{shipId:'two',path:['a','b']}]};
function Harness({options,command=move}:{options:SoundFeedbackOptions;command?:GameCommand}){const feedback=useGameSoundFeedback(options);return <main onClickCapture={feedback.capture} onClick={feedback.clicked}><button onClick={()=>feedback.submitted(command)}>Commit</button><button>Inspect</button><button data-sound="detent">Rotate</button><input aria-label="Notes"/><button data-sound="silent">Preview</button><button>Skip playback</button></main>;}
function options():SoundFeedbackOptions{return {revision:10,connected:true,busy:false,status:'',aiEntry:null,aiVisible:true,reviewing:false};}
function mount(initial=options()){const scope=`sound-test-${testScope++}`;const ui=render(<DiceRollScopeContext.Provider value={scope}><Harness options={initial}/></DiceRollScopeContext.Provider>);return {rerender:(next:SoundFeedbackOptions)=>ui.rerender(<DiceRollScopeContext.Provider value={scope}><Harness options={next}/></DiceRollScopeContext.Provider>),unmount:ui.unmount};}
beforeEach(()=>{vi.clearAllMocks();Object.defineProperty(document,'hidden',{configurable:true,value:false});});afterEach(cleanup);
it('suppresses commit click and emits one movement-group cue only after receipt and authoritative view',()=>{const base=options(),ui=mount(base);fireEvent.click(screen.getByText('Commit'));expect(audio.play).not.toHaveBeenCalled();ui.rerender({...base,receipt:{type:'move',revision:11}});expect(audio.play).not.toHaveBeenCalled();ui.rerender({...base,revision:11,receipt:{type:'move',revision:11}});expect(audio.play).toHaveBeenCalledExactlyOnceWith('move');ui.rerender({...base,revision:12,receipt:{type:'move',revision:11}});expect(audio.play).toHaveBeenCalledTimes(1);});
it('plays selection and rotation only for meaningful activations, never hover, typing or scroll',()=>{mount();fireEvent.mouseOver(screen.getByText('Inspect'));fireEvent.change(screen.getByLabelText('Notes'),{target:{value:'hello'}});fireEvent.scroll(screen.getByRole('main'));fireEvent.click(screen.getByText('Preview'));expect(audio.play).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Inspect'));fireEvent.click(screen.getByText('Rotate'));expect(audio.play.mock.calls).toEqual([['selection'],['detent']]);});
it('rejects a failed submission without a success cue',()=>{const base=options(),ui=mount(base);fireEvent.click(screen.getByText('Commit'));ui.rerender({...base,busy:true});ui.rerender({...base,status:'The action is no longer legal.'});expect(audio.play).toHaveBeenCalledExactlyOnceWith('reject');ui.rerender({...base,status:'The action is no longer legal.'});expect(audio.play).toHaveBeenCalledTimes(1);});
it.each(['hidden','history','reconnect'] as const)('consumes %s receipts without a catch-up sound',mode=>{const base=options(),ui=mount(base);fireEvent.click(screen.getByText('Commit'));if(mode==='hidden'){Object.defineProperty(document,'hidden',{configurable:true,value:true});fireEvent(document,new Event('visibilitychange'));}if(mode==='reconnect')ui.rerender({...base,connected:false});ui.rerender({...base,revision:11,reviewing:mode==='history',receipt:{type:'move',revision:11}});Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));ui.rerender({...base,revision:11,receipt:{type:'move',revision:11}});expect(audio.play).not.toHaveBeenCalled();});
const entry=(revision:number)=>({revision,actorSeatId:'ai',presentation:{kind:'move',sectorIds:['a','b'],shipIds:['one']}} as PublicHistoryEntry);
it('only sounds fresh visible public AI playback once, not old entry review or history catch-up',()=>{const base=options(),ui=mount({...base,aiEntry:entry(10)});expect(audio.play).not.toHaveBeenCalled();ui.rerender({...base,revision:11,aiEntry:entry(11),aiVisible:false});ui.rerender({...base,revision:11,aiEntry:entry(11),aiVisible:true});expect(audio.play).not.toHaveBeenCalled();ui.rerender({...base,revision:12,aiEntry:entry(12)});expect(audio.play).toHaveBeenCalledExactlyOnceWith('move');ui.rerender({...base,revision:15,aiEntry:entry(14)});expect(audio.play).toHaveBeenCalledTimes(1);});
it('cancels running sounds on visibility loss and unmount',()=>{const ui=mount();act(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});expect(audio.stop).toHaveBeenCalled();audio.stop.mockClear();ui.unmount();expect(audio.stop).toHaveBeenCalledOnce();});

it('skip stops the current effect without starting a replacement click',()=>{mount();fireEvent.click(screen.getByText('Skip playback'));expect(audio.stop).toHaveBeenCalledOnce();expect(audio.play).not.toHaveBeenCalled();});
