// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import GameSettingsPanel from '../second-dawn-game/GameSettingsPanel';
import {useGameEffectsEnabled,useGameEffectsVolume,useAmbientEnabled,useAmbientVolume} from '../second-dawn-game/presentationSettings';
function Settings(){return <GameSettingsPanel motionEnabled={false} onMotionChange={()=>{}} onClose={()=>{}}/>;}
function Consumer(){const [effects,setEffects]=useGameEffectsEnabled(),[volume,setVolume]=useGameEffectsVolume(),[music,setMusic]=useAmbientEnabled(),[musicVolume,setMusicVolume]=useAmbientVolume();return <><output>{`${effects}/${volume}/${music}/${musicVolume}`}</output><button onClick={()=>{setEffects(true);setVolume(.2);setMusic(true);setMusicVolume(.1);}}>Enable new audio</button></>;}
afterEach(()=>{cleanup();vi.restoreAllMocks();localStorage.clear();});
it('new channels default off at independent low levels without changing dice or motion',()=>{render(<Settings/>);expect(screen.getByRole('checkbox',{name:/Game effects/})).not.toBeChecked();expect(screen.getByRole('checkbox',{name:/Ambient music/})).not.toBeChecked();expect(screen.getByRole('slider',{name:'Game effects volume'})).toHaveValue('35');expect(screen.getByRole('slider',{name:'Ambient music volume'})).toHaveValue('15');expect(screen.getByRole('checkbox',{name:/Dice sounds/})).toBeChecked();expect(screen.getByRole('slider',{name:'Dice volume'})).toHaveValue('60');expect(screen.getByRole('checkbox',{name:/Animations/})).not.toBeChecked();});
it('saves new channels independently and synchronizes consumers and other tabs',()=>{const ui=render(<><Consumer/><Consumer/></>);fireEvent.click(screen.getAllByText('Enable new audio')[0]);expect(screen.getAllByText('true/0.2/true/0.1')).toHaveLength(2);localStorage.setItem('eclipse.second-dawn.effects.v1','off');fireEvent(window,new Event('storage'));expect(screen.getAllByText('false/0.2/true/0.1')).toHaveLength(2);ui.unmount();render(<Consumer/>);expect(screen.getByText('false/0.2/true/0.1')).toBeInTheDocument();});
it('retains a session preference if storage is blocked',()=>{vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw new Error('blocked');});vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('blocked');});const ui=render(<Consumer/>);fireEvent.click(screen.getByText('Enable new audio'));ui.unmount();render(<Consumer/>);expect(screen.getByText('true/0.2/true/0.1')).toBeInTheDocument();});
