import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {getPlayerView} from '../../shared/eclipse/protocol';
import {legalCommands} from '../../shared/eclipse/legal';
import type {GameState} from '../../shared/eclipse/types';
import fixturesJson from '../second-dawn-game/reviewFixtures.json?raw';
import SecondDawnBoard from '../second-dawn-game/SecondDawnBoard';
import {emptyActionDrafts,readActionDrafts,setDraftValue,writeActionDrafts} from '../second-dawn-game/actionDraftStorage';
afterEach(()=>{cleanup();localStorage.clear();vi.unstubAllGlobals();});
it('inspects sectors on mobile during an exchange without exposing or altering a restored build order',()=>{
 vi.stubGlobal('matchMedia',vi.fn((query:string)=>({matches:query.includes('max-width'),media:query,addEventListener:vi.fn(),removeEventListener:vi.fn()})));
 const state=(JSON.parse(fixturesJson) as Record<string,GameState>).diplomacy;
 const view=getPlayerView(state,state.pendingDecision!.owner)!;
 const partition={matchId:'ambassador-with-build-draft',viewerSeatId:view.viewerSeatId};
 const order={items:[{id:'saved-interceptor',component:'interceptor' as const,sectorId:view.sectors[0].id}],selectedItemId:null,fundingKey:''};
 let snapshot=emptyActionDrafts(partition);
 snapshot=setDraftValue(snapshot,'buildOpen',true,view.revision-1);
 snapshot=setDraftValue(snapshot,'buildOrder',order,view.revision-1);
 writeActionDrafts(localStorage,snapshot);
 const submit=vi.fn();
 const {container}=render(<SecondDawnBoard matchId={partition.matchId} view={view} candidates={legalCommands(view)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);
 fireEvent.click(screen.getByRole('radio',{name:'Science'}));
 fireEvent.click(screen.getByRole('button',{name:'View galaxy'}));
 const map=screen.getByRole('group',{name:'Galaxy map'});
 expect(screen.queryByRole('button',{name:/Relocate planned/})).toBeNull();
 expect(container.querySelector('main')).not.toHaveClass('dg-build-mode');
 fireEvent.click(within(map).getAllByRole('button',{name:/^Inspect sector /})[0]);
 expect(screen.getByRole('complementary',{name:'Selection and action details'})).toHaveAttribute('data-sheet-state','peek');
 expect(submit).not.toHaveBeenCalled();
 expect(readActionDrafts(localStorage,partition).values.buildOrder?.value).toEqual(order);
 fireEvent.click(screen.getByRole('button',{name:'Return to ambassador exchange'}));
 expect(screen.getByRole('radio',{name:'Science'})).toHaveAttribute('aria-checked','true');
});
