import {render,screen,within,fireEvent,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import {legalCommands} from '../../shared/eclipse/legal';
import SecondDawnBoard from '../second-dawn-game/SecondDawnBoard';
afterEach(cleanup);
function view(){const state=createGame({seed:9,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'eridani',controller:'ai'}]});state.seats[0].resources.money=2;state.seats[0].populationTracks.money=1;state.seats[0].influenceOnTrack=7;return getPlayerView(state,'a')!;}
it('shows an action-induced upkeep shortfall before the player chooses or commits a build',()=>{const v=view(),submit=vi.fn();render(<SecondDawnBoard view={v} candidates={legalCommands(v)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Build',exact:true}));const cost=screen.getByRole('region',{name:'Action cost preview'});expect(within(cost).getByText('Round-end upkeep: 5 → 7 money')).toBeInTheDocument();expect(within(cost).getByText('2 short')).toBeInTheDocument();expect(submit).not.toHaveBeenCalled();expect(v.seats[0].resources.money).toBe(2);});
it('clears a previous End action workflow when AI turns return control to the player',()=>{const v=view();v.actionProgress={owner:'a',action:'move',remaining:1};const props={connected:true,busy:false,status:'',onSubmit:vi.fn(),onMenu:vi.fn()};const r=render(<SecondDawnBoard {...props} view={v} candidates={legalCommands(v)}/>);fireEvent.click(screen.getByRole('button',{name:'End action',exact:true}));const next={...v,activeSeatId:'b',actionProgress:null};r.rerender(<SecondDawnBoard {...props} view={next} candidates={[]}/>);const returned={...next,activeSeatId:'a'};r.rerender(<SecondDawnBoard {...props} view={returned} candidates={legalCommands(returned)}/>);expect(screen.queryByText('END ACTION')).toBeNull();expect(within(screen.getByRole('complementary',{name:'Selection and action details'})).getByText('EXPLORE',{exact:true})).toBeInTheDocument();});
