import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import {legalCommands} from '../../shared/eclipse/legal';
import {fundedCandidates} from '../second-dawn-game/fundedCandidates';
import SecondDawnBoard from '../second-dawn-game/SecondDawnBoard';
afterEach(cleanup);
function fixture(){const state=createGame({seed:42,seats:[{id:'a',faction:'terran-directorate',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});state.activeSeatId='a';state.technologyMarket=['fusion-drive'];state.seats[0].resources={money:4,science:1,materials:2};return state;}
it('shows a conversion warning and submits one atomic research command only after confirmation',()=>{const view=getPlayerView(fixture(),'a')!,submit=vi.fn();render(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);fireEvent.click(screen.getAllByRole('button',{name:'Research',exact:true})[0]);fireEvent.click(screen.getByRole('button',{name:/Fusion Drive ×/}));expect(screen.getByText('Conversion required')).toBeInTheDocument();expect(screen.getByRole('img',{name:'Spend 4 money'})).toBeInTheDocument();expect(screen.getByRole('img',{name:'Spend 2 materials'})).toBeInTheDocument();expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Convert & research'}));expect(submit).toHaveBeenCalledTimes(1);expect(submit.mock.calls[0][0]).toMatchObject({type:'trade-and-act',action:{type:'research',tileId:'fusion-drive'},trades:[{from:'money',to:'science',amount:2},{from:'materials',to:'science',amount:1}]});});
it('offers funded builds but filters unaffordable purchases and illegal action continuations',()=>{const state=fixture();let view=getPlayerView(state,'a')!;expect(fundedCandidates(view).some(c=>c.command.action.type==='build')).toBe(true);state.engine!.action={owner:'a',action:'move',remaining:1};view=getPlayerView(state,'a')!;expect(fundedCandidates(view)).toEqual([]);state.engine!.action=null;state.seats[0].resources={money:0,science:1,materials:0};expect(fundedCandidates(getPlayerView(state,'a')!)).toEqual([]);});
it('allows choosing a different input mix without committing a trade',()=>{const state=fixture();state.seats[0].resources={money:8,science:1,materials:8};const view=getPlayerView(state,'a')!,submit=vi.fn();render(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);fireEvent.click(screen.getAllByRole('button',{name:'Research',exact:true})[0]);fireEvent.click(screen.getByRole('button',{name:/Fusion Drive ×/}));fireEvent.click(screen.getByRole('button',{name:'Pay 6 money'}));expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Convert & research'}));expect(submit.mock.calls[0][0].trades).toEqual([{from:'money',to:'science',amount:3}]);});
