// @vitest-environment jsdom
import {fireEvent,render,screen} from '@testing-library/react';
import {expect,it,vi} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import HistoryPanel from '../second-dawn-game/HistoryPanel';
import ActivityRecap from '../second-dawn-game/ActivityRecap';
import PublicInspectionModal from '../second-dawn-game/PublicInspectionModal';
import {PublicInspectionProvider} from '../second-dawn-game/PublicInspectionContext';
import {historyPresentationLines,scoreInspection} from '../second-dawn-game/publicInspection';
const view=()=>getPlayerView(createGame({seed:3,seats:[{id:'a',faction:'terran-directorate',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]}),'a')!;
it('opens a keyboard-safe public history reference without altering its public details',()=>{const entry={revision:4,actorSeatId:'a',actorName:'Terran',round:1,summary:'Built a component',details:['Built interceptor in sector 221.'],presentation:{kind:'build' as const,sectorIds:[view().sectors[0].id],components:[{type:'interceptor' as const,count:1}]}};render(<PublicInspectionProvider><HistoryPanel feed={{entries:[entry],loading:false,hasOlder:false,loadingOlder:false,error:null,loadOlder:vi.fn()}}/><PublicInspectionModal view={view()}/></PublicInspectionProvider>);const trigger=screen.getByRole('button',{name:'Inspect public reference'});trigger.focus();fireEvent.click(trigger);const dialog=screen.getByRole('dialog',{name:'Public history inspection'});expect(dialog).toHaveTextContent(/Ships and control may have changed/);expect(dialog).toHaveTextContent('1 interceptor built');expect(dialog).toHaveFocus();fireEvent.keyDown(dialog,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(trigger).toHaveFocus();});
it('reconciles public score category values with the running score',()=>{const current=view(),detail=scoreInspection(current,'a','sectors');expect(detail.value).toBeGreaterThanOrEqual(0);expect(detail.sectorIds).toEqual(current.sectors.filter(sector=>sector.owner==='a').map(sector=>sector.id));});
it('lists public research tracks and their exact threshold contribution',()=>{const current=view();current.seats.find(seat=>seat.id==='a')!.technologies.military=['plasma-cannon','soliton-cannon','antimatter-cannon','plasma-missile'];const detail=scoreInspection(current,'a','research');expect(detail.value).toBe(1);expect(detail.contributors.join(' ')).toMatch(/military: 4 technologies · 1 VP.*Plasma Cannon/);});
it('provides concrete public research and upgrade history labels',()=>{expect(historyPresentationLines({revision:1,actorSeatId:'a',actorName:'Terran',round:1,summary:'Researched',details:[],presentation:{kind:'research',technologyId:'plasma-cannon'}})).toEqual(['Plasma Cannon']);expect(historyPresentationLines({revision:2,actorSeatId:'a',actorName:'Terran',round:1,summary:'Upgraded',details:[],presentation:{kind:'upgrade',shipTypes:['interceptor','cruiser']} })).toEqual(['Interceptor blueprint updated','Cruiser blueprint updated']);});
it('keeps recap inspection optional and shows an important public activity count',()=>{const entry={revision:4,actorSeatId:'a',actorName:'Terran',round:1,summary:'Passed',details:[]};render(<PublicInspectionProvider><ActivityRecap baseline={null} throughRevision={4} feed={{entries:[entry],loading:false,hasOlder:false,loadingOlder:false,error:null,loadOlder:vi.fn()}} disabled={false} saving={false} error={null} onDismiss={vi.fn()}/></PublicInspectionProvider>);expect(screen.getByText('1 public action in this return window.')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Inspect public reference'})).toBeInTheDocument();});
