// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import type {PlayerView} from '../../shared/eclipse/types';
import TurnAttentionNotice from '../second-dawn-game/TurnAttentionNotice';
function fixture():PlayerView{return {...getPlayerView(createGame({seed:13,seats:[{id:'a',faction:'eridani',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]}),'a')!,activeSeatId:'a'};}
const open=vi.fn(),upkeep=vi.fn();
function notice(view:PlayerView,extra:{matchScope?:string;connected?:boolean;suppressed?:boolean}={}){return <TurnAttentionNotice view={view} matchScope="match-a" onOpenTurn={open} onReviewUpkeep={upkeep} {...extra}/>;}
beforeEach(()=>{vi.clearAllMocks();Object.defineProperty(document,'hidden',{configurable:true,value:false});});afterEach(cleanup);
it('announces an initial human turn without taking focus or calling navigation',()=>{const field=document.createElement('input');document.body.append(field);field.focus();render(notice(fixture()));expect(screen.getByRole('status')).toHaveTextContent('Your turn');expect(field).toHaveFocus();expect(open).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'View turn'}));expect(open).toHaveBeenCalledOnce();expect(upkeep).not.toHaveBeenCalled();expect(screen.queryByRole('status')).not.toBeInTheDocument();field.remove();});
it('does not recreate a dismissed notice on unrelated revisions or action progress',()=>{const view=fixture(),ui=render(notice(view));fireEvent.click(screen.getByRole('button',{name:'Dismiss turn notice'}));ui.rerender(notice({...view,revision:50,actionProgress:{owner:'a',action:'build',remaining:1}}));expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('announces AI-to-human transitions again after the prior turn was dismissed',()=>{const view=fixture(),ui=render(notice({...view,activeSeatId:'b'}));expect(screen.queryByRole('status')).not.toBeInTheDocument();ui.rerender(notice(view));expect(screen.getByRole('status')).toHaveTextContent('Your turn');fireEvent.click(screen.getByRole('button',{name:'Dismiss turn notice'}));ui.rerender(notice({...view,activeSeatId:'b'}));ui.rerender(notice(view));expect(screen.getByRole('status')).toHaveTextContent('Your turn');});
it('uses the explicit action serial for consecutive same-owner turns and resets for a new scope',()=>{const view=fixture(),ui=render(notice({...view,actionTurnSerial:5}));fireEvent.click(screen.getByRole('button',{name:'Dismiss turn notice'}));ui.rerender(notice({...view,actionTurnSerial:6}));expect(screen.getByRole('status')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Dismiss turn notice'}));ui.rerender(notice({...view,actionTurnSerial:6},{matchScope:'match-b'}));expect(screen.getByRole('status')).toBeInTheDocument();});
it('offers upkeep review only to its active player and never finishes upkeep automatically',()=>{const view={...fixture(),phase:'upkeep' as const},ui=render(notice({...view,activeSeatId:'b'}));expect(screen.queryByRole('status')).not.toBeInTheDocument();ui.rerender(notice(view));expect(screen.getByRole('status')).toHaveTextContent('Upkeep is ready');expect(upkeep).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Review upkeep'}));expect(upkeep).toHaveBeenCalledOnce();expect(open).not.toHaveBeenCalled();expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('announces a new round and upkeep phase without requiring a revision change',()=>{const view=fixture(),ui=render(notice(view));fireEvent.click(screen.getByRole('button',{name:'Dismiss turn notice'}));ui.rerender(notice({...view,round:view.round+1}));expect(screen.getByRole('status')).toHaveTextContent('Your turn');ui.rerender(notice({...view,phase:'upkeep'}));expect(screen.getByRole('status')).toHaveTextContent('Upkeep is ready');});
it('waits while hidden and shows only current ownership on return',()=>{const view=fixture();Object.defineProperty(document,'hidden',{configurable:true,value:true});const ui=render(notice({...view,activeSeatId:'b'}));ui.rerender(notice(view));expect(screen.queryByRole('status')).not.toBeInTheDocument();Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));expect(screen.getByRole('status')).toHaveTextContent('Your turn');Object.defineProperty(document,'hidden',{configurable:true,value:true});fireEvent(document,new Event('visibilitychange'));ui.rerender(notice({...view,activeSeatId:'b'}));Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('keeps a dismissal when returning to the same turn after hiding',()=>{render(notice(fixture()));fireEvent.click(screen.getByRole('button',{name:'Dismiss turn notice'}));Object.defineProperty(document,'hidden',{configurable:true,value:true});fireEvent(document,new Event('visibilitychange'));Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('leaves deliberate decisions in charge and does not show a stale toast after their resolution',()=>{const view=fixture(),decision={id:'decision',kind:'reputation' as const,owner:'a',drawn:[1],capacity:5};const ui=render(notice({...view,pendingDecision:decision}));expect(screen.queryByRole('status')).not.toBeInTheDocument();ui.rerender(notice(view));expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('suppresses behind other UI until it is available and removes stale ownership immediately',()=>{const view=fixture(),ui=render(notice(view,{suppressed:true}));expect(screen.queryByRole('status')).not.toBeInTheDocument();ui.rerender(notice(view));expect(screen.getByRole('status')).toBeInTheDocument();ui.rerender(notice({...view,activeSeatId:'b'}));expect(screen.queryByRole('status')).not.toBeInTheDocument();});
it('does not prompt disconnected, finished, waiting-on-opponent or eliminated viewers',()=>{const view=fixture(),ui=render(notice(view,{connected:false}));expect(screen.queryByRole('status')).not.toBeInTheDocument();for(const state of [{...view,phase:'finished' as const},{...view,waitingFor:{owner:'b',kind:'diplomacy' as const}},{...view,seats:view.seats.map(seat=>seat.id==='a'?{...seat,eliminated:true}:seat)}]){ui.rerender(notice(state));expect(screen.queryByRole('status')).not.toBeInTheDocument();}});
it('clears the turn notice once an action begins and keeps its planner unobstructed',()=>{const view=fixture(),ui=render(notice(view));expect(screen.getByRole('status')).toBeInTheDocument();ui.rerender(notice({...view,revision:1,actionProgress:{owner:'a',action:'build',remaining:1}}));expect(screen.queryByRole('status')).not.toBeInTheDocument();ui.rerender(notice({...view,revision:2}));expect(screen.queryByRole('status')).not.toBeInTheDocument();});
