import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import {legalCommands} from '../../shared/eclipse/legal';
import type {PendingDecision} from '../../shared/eclipse/types';
import EconomyDecision from '../second-dawn-game/EconomyDecision';
afterEach(cleanup);
it('previews the selected warp portal and its destinations before committing',()=>{
 const state=createGame({seed:42,warpPortals:true,seats:[{id:'a',faction:'terran-directorate',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});
 const home=state.sectors.find(s=>s.owner==='a')!,other=state.sectors.find(s=>s.owner==='b')!;other.portalVp=1;
 const decision:PendingDecision={id:'portal',owner:'a',kind:'portal-placement',sectorIds:[home.id]};state.pendingDecision=decision;
 const view=getPlayerView(state,'a')!,submit=vi.fn();render(<EconomyDecision view={view} candidates={legalCommands(view)} decision={decision} reputation={[]} disabled={false} onSubmit={submit}/>);
 fireEvent.click(within(screen.getByRole('group',{name:'Eligible sectors'})).getByRole('button'));
 expect(screen.getByRole('region',{name:'Preview portal connections'})).toHaveTextContent(other.tileId);
 expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Place warp portal'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'resolve',decisionId:'portal',choice:{kind:'portal-placement',sectorId:home.id}});
});
function fixture(decision:PendingDecision){const state=createGame({seed:42,seats:[{id:'a',faction:'terran-directorate',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});state.pendingDecision=decision;const view=getPlayerView(state,'a')!;return {view,candidates:legalCommands(view)};}
it('allocates a mixed resource reward visually and commits the exact choices once',()=>{const decision:PendingDecision={id:'reward',owner:'a',kind:'resource-reward',count:2,perChoice:5};const props=fixture(decision),submit=vi.fn();render(<EconomyDecision {...props} decision={decision} reputation={[]} disabled={false} onSubmit={submit}/>);expect(screen.queryByRole('combobox')).toBeNull();expect(screen.getByRole('button',{name:'Confirm reward'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Add money allocation'}));fireEvent.click(screen.getByRole('button',{name:'Add science allocation'}));expect(screen.getByText('+5 science')).toBeVisible();expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirm reward'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'resolve',decisionId:'reward',choice:{kind:'resource-reward',resources:['money','science']}});});
it('selects a free technology by its effect card and exposes only legal research tracks',()=>{const decision:PendingDecision={id:'free',owner:'a',kind:'free-technology',technologyIds:['fusion-drive','improved-hull']};const props=fixture(decision),submit=vi.fn();render(<EconomyDecision {...props} decision={decision} reputation={[]} disabled={false} onSubmit={submit}/>);fireEvent.click(screen.getByRole('button',{name:'Choose free Fusion Drive'}));expect(screen.getByRole('radio',{name:'Nano'})).toHaveAttribute('aria-checked','true');expect(screen.queryByRole('radio',{name:'Military'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Confirm free technology'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'resolve',decisionId:'free',choice:{kind:'free-technology',technologyId:'fusion-drive',track:'nano'}});});
it('shows a sector and exact control upkeep preview before placing a disc',()=>{const state=createGame({seed:42,seats:[{id:'a',faction:'terran-directorate',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});const sector=state.sectors.find(s=>!s.owner)!;const decision:PendingDecision={id:'control',owner:'a',kind:'control',sectorId:sector.id};state.pendingDecision=decision;const view=getPlayerView(state,'a')!,submit=vi.fn();render(<EconomyDecision view={view} candidates={legalCommands(view)} decision={decision} reputation={[]} disabled={false} onSubmit={submit}/>);fireEvent.click(screen.getByRole('radio',{name:'Place influence disc'}));expect(screen.getByRole('region',{name:'Action cost preview'})).toHaveTextContent('No action disc needed');expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirm control'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'resolve',decisionId:'control',choice:{kind:'control',accept:true}});});
it('keeps reputation as privately selected visual tiles, with at most one new draw',()=>{const decision:PendingDecision={id:'rep',owner:'a',kind:'reputation',drawn:[3,4],capacity:2};const props=fixture(decision),submit=vi.fn();render(<EconomyDecision {...props} decision={decision} reputation={[2]} disabled={false} onSubmit={submit}/>);const drawn=screen.getByRole('group',{name:'Newly drawn reputation'});fireEvent.click(within(drawn).getByRole('checkbox',{name:'Keep 4 VP reputation'}));expect(within(drawn).getByRole('checkbox',{name:'Keep 3 VP reputation'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Confirm reputation'}));expect(submit.mock.calls[0][0].choice.kept).toEqual([2,4]);});
