import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import {legalCommands} from '../../shared/eclipse/legal';
import SecondDawnBoard from '../second-dawn-game/SecondDawnBoard';
afterEach(cleanup);
function fixture(){return createGame({seed:6,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'eridani',controller:'ai'}]});}
it('ends an ordinary action with exactly one click and one command',()=>{const state=fixture();state.engine!.action={owner:'a',action:'move',remaining:1};const view=getPlayerView(state,'a')!,submit=vi.fn();render(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'End action',exact:true}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'end-action'});expect(screen.queryByRole('button',{name:'Confirm action'})).toBeNull();});
it('passes with one click and prevents offline direct submissions',()=>{const view=getPlayerView(fixture(),'a')!,submit=vi.fn();const r=render(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected={false} busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);expect(screen.getByRole('button',{name:'Pass',exact:true})).toBeDisabled();r.rerender(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Pass',exact:true}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'pass'});});
it('keeps one explicit betrayal warning without making the player select a redundant option',()=>{const state=fixture();state.engine!.action={owner:'a',action:'move',remaining:1};state.seats[0].ambassadors=['b'];state.ships.find(s=>s.owner==='a')!.sectorId=state.sectors.find(s=>s.owner==='b')!.id;const view=getPlayerView(state,'a')!,submit=vi.fn();render(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected busy={false} status="" onSubmit={submit} onMenu={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'End action',exact:true}));expect(submit).not.toHaveBeenCalled();expect(screen.queryByRole('combobox')).toBeNull();expect(screen.getByText(/Breaks diplomacy with/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'End action and break diplomacy'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'end-action'});});
