// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { createGame } from '../../shared/eclipse/setup';
import { getPlayerView } from '../../shared/eclipse/protocol';
import type { LegalCommandCandidate } from '../../shared/eclipse/legal';
import TradePanel from '../second-dawn-game/TradePanel';
afterEach(cleanup);
const view=()=>{const state=createGame({seed:1,warpPortals:false,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'planta',controller:'ai'}]});state.seats[0].resources={money:10,science:2,materials:6};return getPlayerView(state,'a')!;};
const candidates:LegalCommandCandidate[]=[{command:{type:'trade',from:'money',to:'science',amount:1},label:'trade',description:''},{command:{type:'trade',from:'materials',to:'science',amount:1},label:'trade',description:''}];
it('drafts multiple trades, previews exact cost and remaining amounts, then confirms once',()=>{const submit=vi.fn();render(<TradePanel view={view()} candidates={candidates} disabled={false} onSubmit={submit}/>);fireEvent.click(screen.getByRole('button',{name:'Increase received amount'}));expect(submit).not.toHaveBeenCalled();expect(screen.getByRole('img',{name:'Spend 6 money'})).toBeTruthy();expect(screen.getByRole('img',{name:'Receive 2 science'})).toBeTruthy();expect(screen.getByText('Money: 10 → 4')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Confirm trade'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'trade',from:'money',to:'science',amount:2});});
it('changes payment source, caps amount by faction ratio, and disables unavailable outputs',()=>{render(<TradePanel view={view()} candidates={candidates} disabled={false} onSubmit={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Pay with materials'}));fireEvent.click(screen.getByRole('button',{name:'Increase received amount'}));expect(screen.getByRole('button',{name:'Increase received amount'}).hasAttribute('disabled')).toBe(true);expect(screen.getByRole('button',{name:'Receive money'}).hasAttribute('disabled')).toBe(true);expect(screen.getByRole('img',{name:'Spend 6 materials'})).toBeTruthy();});
it('honors faction trade ratios and suppresses stale or disconnected submissions',()=>{const current=view();current.seats[0].faction='terran-directorate';const submit=vi.fn();const{rerender}=render(<TradePanel view={current} candidates={candidates} disabled={false} onSubmit={submit}/>);expect(screen.getByRole('img',{name:'Spend 2 money'})).toBeTruthy();rerender(<TradePanel view={current} candidates={[]} disabled={false} onSubmit={submit}/>);expect(screen.getByRole('button',{name:'Confirm trade'}).hasAttribute('disabled')).toBe(true);rerender(<TradePanel view={current} candidates={candidates} disabled onSubmit={submit}/>);fireEvent.click(screen.getByRole('button',{name:'Confirm trade'}));expect(submit).not.toHaveBeenCalled();});
it('switches output resource and applies the Orion four-to-one exchange',()=>{const current=view();current.seats[0].faction='orion';const submit=vi.fn();render(<TradePanel view={current} candidates={[...candidates,{command:{type:'trade',from:'money',to:'materials',amount:1},label:'trade',description:''}]} disabled={false} onSubmit={submit}/>);fireEvent.click(screen.getByRole('button',{name:'Receive materials'}));expect(screen.getByRole('img',{name:'Spend 4 money'})).toBeTruthy();expect(screen.getByRole('img',{name:'Receive 1 materials'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Confirm trade'}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'trade',from:'money',to:'materials',amount:1});});
