import {act,cleanup,render} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import type {GameEvent} from '../../shared/eclipse/types';
import {useCombatVolleySounds} from '../second-dawn-game/sound/useCombatVolleySounds';
const audio=vi.hoisted(()=>({play:vi.fn(),enabled:true,volume:.35}));
vi.mock('../second-dawn-game/sound/runtime',()=>({playCosmeticCue:audio.play}));
vi.mock('../second-dawn-game/presentationSettings',()=>({useDiceRollScope:()=> 'combat-audio-test',useGameEffectsEnabled:()=>[audio.enabled],useGameEffectsVolume:()=>[audio.volume]}));
let serial=0;
const volley=():NonNullable<GameEvent['combatVolley']>=>({battleId:`battle-${serial++}`,attacker:'a',dice:[{id:'missile',face:6,damage:2,computer:0,weaponKind:'missile',weaponColor:'orange'}],impacts:[{dieId:'missile',targetId:'target',hit:true,damage:2}],targets:[{id:'target',hpBefore:2,hpAfter:0,excess:0,destroyed:true}]});
function Harness({event,eligible=true,waiting=false,skip=false}:{event:NonNullable<GameEvent['combatVolley']>;eligible?:boolean;waiting?:boolean;skip?:boolean}){useCombatVolleySounds({volleys:[event],eligible,awaitingDice:waiting,skipped:skip});return null;}
beforeEach(()=>{vi.useFakeTimers();audio.enabled=true;audio.volume=.35;audio.play.mockReset();audio.play.mockImplementation(()=>({stop:vi.fn()}));Object.defineProperty(document,'hidden',{configurable:true,value:false});});afterEach(()=>{cleanup();vi.useRealTimers();});
it('launches after dice settle then sounds a recorded destruction, once',()=>{const event=volley();const ui=render(<Harness event={event} waiting/>);expect(audio.play).not.toHaveBeenCalled();ui.rerender(<Harness event={event}/>);expect(audio.play).toHaveBeenCalledExactlyOnceWith('missile-launch');act(()=>vi.advanceTimersByTime(350));expect(audio.play.mock.calls.map(call=>call[0])).toEqual(['missile-launch','explosion']);ui.rerender(<Harness event={event}/>);act(()=>vi.advanceTimersByTime(1000));expect(audio.play).toHaveBeenCalledTimes(2);});
it('sounds cannon fire and a hit without an explosion for a surviving ship',()=>{const event=volley();event.dice[0].weaponKind='cannon';event.targets[0]={...event.targets[0],destroyed:false,hpAfter:1};render(<Harness event={event}/>);act(()=>vi.advanceTimersByTime(350));expect(audio.play.mock.calls.map(call=>call[0])).toEqual(['cannon-fire','impact']);});
it('does not invent an impact or weapon for misses and legacy records',()=>{const miss=volley();miss.impacts[0].hit=false;miss.targets[0]={...miss.targets[0],destroyed:false,hpAfter:2};render(<Harness event={miss}/>);act(()=>vi.advanceTimersByTime(500));expect(audio.play.mock.calls.map(call=>call[0])).toEqual(['missile-launch']);cleanup();audio.play.mockClear();const legacy=volley();delete legacy.dice[0].weaponKind;legacy.targets=[];legacy.impacts=[];render(<Harness event={legacy}/>);act(()=>vi.advanceTimersByTime(500));expect(audio.play).not.toHaveBeenCalled();});
it.each(['not-live','muted','hidden'] as const)('never replays a %s volley when it later becomes available',mode=>{const event=volley();if(mode==='muted')audio.enabled=false;if(mode==='hidden')Object.defineProperty(document,'hidden',{configurable:true,value:true});const ui=render(<Harness event={event} eligible={mode!=='not-live'}/>);audio.enabled=true;Object.defineProperty(document,'hidden',{configurable:true,value:false});ui.rerender(<Harness event={event}/>);act(()=>vi.advanceTimersByTime(1000));expect(audio.play).not.toHaveBeenCalled();});
it('cancels the scheduled impact and running launch on hide, skip, or unmount',()=>{const event=volley();const ui=render(<Harness event={event}/>);const launch=audio.play.mock.results[0].value;Object.defineProperty(document,'hidden',{configurable:true,value:true});act(()=>document.dispatchEvent(new Event('visibilitychange')));act(()=>vi.advanceTimersByTime(1000));expect(launch.stop).toHaveBeenCalled();expect(audio.play).toHaveBeenCalledTimes(1);ui.unmount();Object.defineProperty(document,'hidden',{configurable:true,value:false});const second=volley();const next=render(<Harness event={second}/>);next.rerender(<Harness event={second} skip/>);act(()=>vi.advanceTimersByTime(1000));expect(audio.play).toHaveBeenCalledTimes(2);});
