import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import AutoPassControl from '../second-dawn-game/AutoPassControl';
afterEach(cleanup);
it('submits a preference once, waits for saved state, and prevents offline changes',()=>{
 const change=vi.fn(),ui=render(<AutoPassControl enabled={false} paused={false} disabled={false} onChange={change}/>);
 const toggle=screen.getByRole('checkbox',{name:'Auto-pass unless attacked'});
 fireEvent.click(toggle);expect(change).toHaveBeenCalledExactlyOnceWith(true);expect(toggle).not.toBeChecked();
 ui.rerender(<AutoPassControl enabled paused={false} disabled onChange={change}/>);
 expect(toggle).toBeChecked();expect(toggle).toBeDisabled();fireEvent.click(toggle);expect(change).toHaveBeenCalledTimes(1);
});
it('explains attack interruption and provides direct resume without requiring an off/on cycle',()=>{
 const change=vi.fn();render(<AutoPassControl enabled paused disabled={false} onChange={change}/>);
 expect(screen.getByRole('status')).toHaveTextContent('Attacked · reactions restored');
 fireEvent.click(screen.getByRole('button',{name:'Resume auto-pass'}));expect(change).toHaveBeenCalledExactlyOnceWith(true);
});
it('lets the player save their own preference while another player acts, without starting an action',async()=>{
 const {createGame}=await import('../../shared/eclipse/setup');
 const {getPlayerView}=await import('../../shared/eclipse/protocol');
 const {default:Board}=await import('../second-dawn-game/SecondDawnBoard');
 const state=createGame({seed:6,warpPortals:true,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'eridani',controller:'ai'}]});state.activeSeatId='b';
 const submit=vi.fn(),props={candidates:[],connected:true,busy:false,status:'Saved',onSubmit:submit,onMenu:vi.fn()};
 const ui=render(<Board view={getPlayerView(state,'a')!} {...props}/>);
 fireEvent.click(screen.getByRole('checkbox',{name:'Auto-pass unless attacked'}));
 expect(submit).toHaveBeenCalledExactlyOnceWith({type:'set-auto-pass',enabled:true});
 state.seats[0].autoPassUnlessAttacked=true;state.revision++;
 ui.rerender(<Board view={getPlayerView(state,'a')!} {...props}/>);
 expect(screen.getByRole('checkbox',{name:'Auto-pass unless attacked'})).toBeChecked();
 ui.rerender(<Board view={getPlayerView(state,'a')!} {...props} connected={false}/>);
 expect(screen.getByRole('checkbox',{name:'Auto-pass unless attacked'})).toBeDisabled();
});
it('keeps auto-pass visible during a build draft and preserves the order through its saved revision',async()=>{
 const {createGame}=await import('../../shared/eclipse/setup');const {getPlayerView}=await import('../../shared/eclipse/protocol');
 const {default:Board}=await import('../second-dawn-game/SecondDawnBoard');
 const state=createGame({seed:6,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'eridani',controller:'ai'}]});
 state.seats[0].resources.materials=20;
 const submit=vi.fn(),props={candidates:[],connected:true,busy:false,status:'Saved',onSubmit:submit,onMenu:vi.fn()};
 const ui=render(<Board view={getPlayerView(state,'a')!} {...props}/>);
 fireEvent.click(screen.getByRole('button',{name:'Build',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Add interceptor'}));
 const toggle=screen.getByRole('checkbox',{name:'Auto-pass unless attacked'});expect(toggle).toBeVisible();fireEvent.click(toggle);
 expect(submit).toHaveBeenCalledExactlyOnceWith({type:'set-auto-pass',enabled:true});
 state.seats[0].autoPassUnlessAttacked=true;state.revision++;
 ui.rerender(<Board view={getPlayerView(state,'a')!} {...props} lastAcceptedCommand={{revision:1,type:'set-auto-pass'}}/>);
 expect(screen.getByRole('checkbox',{name:'Auto-pass unless attacked'})).toBeChecked();expect(screen.getByText(/0 placed · 1 unplaced/)).toBeVisible();
});
it('keeps auto-pass available in empire inspection and does not navigate away when an off-turn preference saves',async()=>{
 const {createGame}=await import('../../shared/eclipse/setup');const {getPlayerView}=await import('../../shared/eclipse/protocol');
 const {default:Board}=await import('../second-dawn-game/SecondDawnBoard');
 const state=createGame({seed:6,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'eridani',controller:'ai'}]});state.activeSeatId='b';
 const submit=vi.fn(),props={candidates:[],connected:true,busy:false,status:'Saved',onSubmit:submit,onMenu:vi.fn()};
 const ui=render(<Board view={getPlayerView(state,'a')!} {...props}/>);
 fireEvent.click(within(screen.getByRole('region',{name:'Civilization roster'})).getByRole('button',{name:/Hydran Progress/}));
 fireEvent.click(screen.getByRole('checkbox',{name:'Auto-pass unless attacked'}));
 state.seats[0].autoPassUnlessAttacked=true;state.revision++;
 ui.rerender(<Board view={getPlayerView(state,'a')!} {...props} lastAcceptedCommand={{revision:1,type:'set-auto-pass'}}/>);
 expect(screen.getByRole('heading',{name:'Hydran Progress',exact:true})).toBeVisible();
 expect(screen.getByRole('checkbox',{name:'Auto-pass unless attacked'})).toBeChecked();
});
it('offers the same auto-pass and follow controls in Settings without closing the dialog',async()=>{
 const {createGame}=await import('../../shared/eclipse/setup');const {getPlayerView}=await import('../../shared/eclipse/protocol');
 const {default:Board}=await import('../second-dawn-game/SecondDawnBoard');
 const state=createGame({seed:6,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'eridani',controller:'ai'}]});state.activeSeatId='b';
 const submit=vi.fn(),props={candidates:[],connected:true,busy:false,status:'Saved',onSubmit:submit,onMenu:vi.fn()};
 const ui=render(<Board view={getPlayerView(state,'a')!} {...props}/>);
 fireEvent.click(screen.getByRole('button',{name:'Settings',exact:true}));const dialog=within(screen.getByRole('dialog',{name:'Game settings'}));
 fireEvent.click(dialog.getByRole('checkbox',{name:/Auto-pass unless attacked/}));expect(submit).toHaveBeenCalledExactlyOnceWith({type:'set-auto-pass',enabled:true});
 state.seats[0].autoPassUnlessAttacked=true;state.revision++;
 ui.rerender(<Board view={getPlayerView(state,'a')!} {...props} lastAcceptedCommand={{revision:1,type:'set-auto-pass'}}/>);
 expect(dialog.getByRole('checkbox',{name:/Auto-pass unless attacked/})).toBeChecked();
 fireEvent.click(dialog.getByRole('checkbox',{name:/Follow AI/}));expect(screen.getByRole('button',{name:'Follow AI'})).toHaveAttribute('aria-pressed','false');
 expect(localStorage.getItem('eclipse.second-dawn.follow-ai.v1')).toBe('off');
});
