// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { createGame } from '../../shared/eclipse/setup';
import { getPlayerView } from '../../shared/eclipse/protocol';
import DiscoveryDecision from '../second-dawn-game/DiscoveryDecision';
import type { PendingDecision } from '../../shared/eclipse/types';
afterEach(cleanup);
function decision(tileId: string, options: ('keep'|'use')[]=['keep','use']): Extract<PendingDecision,{kind:'discovery'}> {return {id:'reward-1',owner:'a',kind:'discovery',tileId,options,sectorId:'sector-42'};}
it('reveals actual cache values before letting the player commit either option',()=>{const submit=vi.fn();render(<DiscoveryDecision decision={decision('mixed-resources')} disabled={false} onSubmit={submit}/>);expect(screen.getByRole('heading',{name:'Resource Cache'})).toBeTruthy();expect(screen.getByLabelText(/Money: \+3/)).toBeTruthy();expect(screen.getByLabelText(/Science: \+2/)).toBeTruthy();expect(screen.getByLabelText(/Materials: \+2/)).toBeTruthy();fireEvent.click(screen.getByRole('radio',{name:/Use Resource Cache/}));expect(submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:/Gain 3 money, 2 science, 2 materials/}));expect(submit).toHaveBeenLastCalledWith({type:'resolve',decisionId:'reward-1',choice:{kind:'discovery',option:'use'}});fireEvent.click(screen.getByRole('radio',{name:/Keep for 2 VP/}));fireEvent.click(screen.getByRole('button',{name:'Keep for 2 VP'}));expect(submit).toHaveBeenLastCalledWith({type:'resolve',decisionId:'reward-1',choice:{kind:'discovery',option:'keep'}});});
it('explains an ancient part and the subsequent free install or storage choice',()=>{render(<DiscoveryDecision decision={decision('axion-computer')} disabled={false} onSubmit={vi.fn()}/>);expect(screen.getByRole('group',{name:'Axion Computer statistics'})).toBeTruthy();expect(screen.getByText(/install it for free.*store it/)).toBeTruthy();});
it('describes free technology selection without implying any technology is available',()=>{render(<DiscoveryDecision decision={decision('ancient-tech')} disabled={false} onSubmit={vi.fn()}/>);expect(screen.getByText(/lowest printed cost.*unowned regular/)).toBeTruthy();});
it('shows portal points as sector-controlled VP rather than guaranteed personal VP',()=>{render(<DiscoveryDecision decision={decision('ancient-warp-portal')} disabled={false} onSubmit={vi.fn()}/>);expect(screen.getByText(/final controller.*2 VP/)).toBeTruthy();});
it('honors restricted choices and disconnection without silently selecting a reward',()=>{render(<DiscoveryDecision decision={decision('ancient-monolith',['keep'])} disabled={true} onSubmit={vi.fn()}/>);expect(screen.getByRole('radio',{name:/Use Ancient Monolith/})).toBeDisabled();expect(screen.queryByRole('button',{name:/Place free monolith/})).toBeNull();});

it('explains the orbital population step and actual materials bonus',()=>{render(<DiscoveryDecision decision={decision('ancient-orbital')} disabled={false} onSubmit={vi.fn()}/>);expect(screen.getByLabelText(/Materials: \+2/)).toBeTruthy();expect(screen.getByText(/not populated automatically/)).toBeTruthy();});
it('requires an explicit side selection before confirmation',()=>{render(<DiscoveryDecision decision={decision('money')} disabled={false} onSubmit={vi.fn()}/>);expect(screen.queryByRole('button',{name:/Gain 8 money/})).toBeNull();expect(screen.getByRole('radio',{name:/Use Money Cache/})).not.toBeChecked();});

it('places the actual reward confirmation inside the chosen discovery card',()=>{const submit=vi.fn();render(<DiscoveryDecision decision={decision('money')} disabled={false} onSubmit={submit}/>);fireEvent.click(screen.getByRole('radio',{name:/Use Money Cache/}));const action=screen.getByRole('button',{name:/Gain 8 money/i});expect(action.closest('section')).toBe(screen.getByRole('radio',{name:/Use Money Cache/}).closest('section'));fireEvent.click(action);expect(submit).toHaveBeenCalledWith({type:'resolve',decisionId:'reward-1',choice:{kind:'discovery',option:'use'}});});

it('blocks an unusable Ancient Tech reward with a specific explanation',()=>{const state=createGame({seed:1,warpPortals:false,seats:[{id:'a',faction:'planta',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});state.technologyMarket=[];render(<DiscoveryDecision view={getPlayerView(state,'a')} decision={decision('ancient-tech')} disabled={false} onSubmit={vi.fn()}/>);expect(screen.getByRole('radio',{name:/Use Ancient Tech/})).toBeDisabled();expect(screen.getByText(/No eligible lowest-cost technology remains/)).toBeTruthy();});
