// @vitest-environment jsdom
import {act,cleanup,fireEvent,render} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const audio=vi.hoisted(()=>({ambient:false,volume:.15,dice:false,effects:false,prepare:vi.fn(),bus:vi.fn(),subscribe:vi.fn(),stopDice:vi.fn(),stopEffects:vi.fn(),synthesize:vi.fn()}));
vi.mock('../second-dawn-game/presentationSettings',()=>({useAmbientEnabled:()=>[audio.ambient],useAmbientVolume:()=>[audio.volume],useDiceSoundEnabled:()=>[audio.dice],useGameEffectsEnabled:()=>[audio.effects],useGameEffectsVolume:()=>[.35]}));
vi.mock('../second-dawn-game/dice3d/audio',()=>({onDiceImpact:audio.subscribe,prepareCosmeticAudio:audio.prepare,preparedAudioBus:audio.bus,stopAllDiceAudio:audio.stopDice}));
vi.mock('../second-dawn-game/sound/runtime',()=>({stopCosmeticCues:audio.stopEffects}));
vi.mock('../second-dawn-game/sound/synthesis',()=>({synthesizeAmbient:audio.synthesize}));
import {useSoundscape} from '../second-dawn-game/sound/useSoundscape';
function Harness(){useSoundscape();return null;}
const parameter={value:0,setTargetAtTime:vi.fn(),cancelScheduledValues:vi.fn()},gain={gain:parameter,connect:vi.fn(),disconnect:vi.fn()},context={currentTime:0,createGain:vi.fn(()=>gain)};
beforeEach(()=>{vi.clearAllMocks();audio.ambient=false;audio.volume=.15;audio.dice=false;audio.effects=false;audio.bus.mockReturnValue({context,output:{}});audio.subscribe.mockReturnValue(vi.fn());audio.prepare.mockResolvedValue(true);audio.synthesize.mockImplementation(()=>({stop:vi.fn()}));Object.defineProperty(document,'hidden',{configurable:true,value:false});});afterEach(cleanup);
it('does not unlock or synthesize by default, starts one bed when enabled and updates gain without restarting',()=>{const ui=render(<Harness/>);fireEvent.pointerDown(window);expect(audio.prepare).not.toHaveBeenCalled();expect(audio.synthesize).not.toHaveBeenCalled();audio.ambient=true;ui.rerender(<Harness/>);expect(audio.synthesize).toHaveBeenCalledOnce();audio.volume=.2;ui.rerender(<Harness/>);expect(parameter.setTargetAtTime).toHaveBeenCalledWith(.2,0,.15);expect(audio.synthesize).toHaveBeenCalledOnce();audio.effects=true;ui.rerender(<Harness/>);fireEvent.pointerDown(window);expect(audio.prepare).toHaveBeenCalledOnce();expect(audio.synthesize).toHaveBeenCalledOnce();});
it('stops on hidden, restarts a fresh bed on return, fades on leave and ignores old loop callbacks',()=>{audio.ambient=true;const ui=render(<Harness/>);const oldLoop=audio.synthesize.mock.calls[0][2];Object.defineProperty(document,'hidden',{configurable:true,value:true});fireEvent(document,new Event('visibilitychange'));expect(audio.synthesize.mock.results[0].value.stop).toHaveBeenCalledWith(0);act(()=>oldLoop());expect(audio.synthesize).toHaveBeenCalledOnce();Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));expect(audio.synthesize).toHaveBeenCalledTimes(2);const currentLoop=audio.synthesize.mock.calls[1][2];ui.unmount();expect(audio.synthesize.mock.results[1].value.stop).toHaveBeenCalledWith(.25);act(()=>currentLoop());expect(audio.synthesize).toHaveBeenCalledTimes(2);});
it('ducks the music under dice and returns smoothly to its saved level',()=>{audio.ambient=true;render(<Harness/>);act(()=>audio.subscribe.mock.calls[0][0]());expect(parameter.setTargetAtTime).toHaveBeenCalledWith(.15*.28,0,.025);expect(parameter.setTargetAtTime).toHaveBeenCalledWith(.15,.3,.3);});
it('a browser synthesis failure is a silent fallback without blocking the match',()=>{audio.ambient=true;audio.synthesize.mockImplementation(()=>{throw new Error('Audio unavailable');});expect(()=>render(<Harness/>)).not.toThrow();});
it('fades immediately on route departure even while a lazy replacement delays unmount',()=>{window.history.replaceState(null,'','#second-dawn-preview');audio.ambient=true;render(<Harness/>);window.history.replaceState(null,'','/');fireEvent(window,new Event('hashchange'));expect(audio.synthesize.mock.results[0].value.stop).toHaveBeenCalledWith(.25);fireEvent.pointerDown(window);expect(audio.synthesize).toHaveBeenCalledOnce();});
