// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { createGame } from '../../shared/eclipse/setup';
import ResearchedTechnologies from '../second-dawn-game/ResearchedTechnologies';
afterEach(cleanup);
it('shows owned technologies in their actual tracks including rare tiles',()=>{const seat=createGame({seed:1,warpPortals:false,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'planta',controller:'ai'}]}).seats[0];seat.technologies={military:['plasma-cannon'],grid:['gluon-computer'],nano:['conifold-field']};const inspect=vi.fn();render(<ResearchedTechnologies seat={seat} onInspect={inspect}/>);expect(screen.getByRole('heading',{name:'Your researched technologies'})).toBeTruthy();expect(screen.getByRole('group',{name:'Military · 1 researched'})).toBeTruthy();expect(screen.getByRole('group',{name:'Nano · 1 researched'})).toBeTruthy();expect(screen.getByRole('group',{name:'Gluon Computer statistics'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Inspect researched Conifold Field'}));expect(inspect).toHaveBeenCalledWith('conifold-field');});
it('makes empty tracks and collapsed ownership counts explicit',()=>{const seat=createGame({seed:1,warpPortals:false,seats:[{id:'a',faction:'planta',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]}).seats[0];seat.technologies={military:[],grid:[],nano:[]};render(<ResearchedTechnologies seat={seat}/>);expect(screen.getAllByText('No technologies yet')).toHaveLength(3);expect(screen.getByText('0 researched · effects apply')).toBeTruthy();});
it('keeps rules accessible even without an inspector callback',()=>{const seat=createGame({seed:1,warpPortals:false,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'planta',controller:'ai'}]}).seats[0];seat.technologies={military:[],grid:['gluon-computer'],nano:[]};render(<ResearchedTechnologies seat={seat}/>);fireEvent.click(screen.getByRole('button',{name:'Inspect researched Gluon Computer'}));expect(screen.getByText(/\+3 to attack rolls/)).toBeTruthy();});
it('clears an owned tile highlight when external inspector selection changes',()=>{const seat=createGame({seed:1,warpPortals:false,seats:[{id:'a',faction:'hydran',controller:'human'},{id:'b',faction:'planta',controller:'ai'}]}).seats[0];seat.technologies={military:['plasma-cannon'],grid:[],nano:[]};const{rerender}=render(<ResearchedTechnologies seat={seat} selectedId="plasma-cannon" onInspect={vi.fn()}/>);expect(screen.getByRole('button',{name:'Inspect researched Plasma Cannon'}).getAttribute('aria-pressed')).toBe('true');rerender(<ResearchedTechnologies seat={seat} selectedId="gluon-computer" onInspect={vi.fn()}/>);expect(screen.getByRole('button',{name:'Inspect researched Plasma Cannon'}).getAttribute('aria-pressed')).toBe('false');});
