import {describe,it,expect} from 'vitest';
import {createGame} from '../../shared/eclipse/setup';
import {getPlayerView} from '../../shared/eclipse/protocol';
import {movementBattleEstimate} from '../../shared/eclipse/movementBattleEstimate';
function fixture(){const state=createGame({seed:42,seats:[{id:'a',faction:'orion',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});const view=getPlayerView(state,'a');return {state,view,ship:view.ships.find(ship=>ship.owner==='a')!,target:view.sectors.find(sector=>sector.owner==='b')!};}
describe('public movement battle estimates',()=>{
 it('estimates selected ships without changing public data or authoritative random state',async()=>{const {state,view,ship,target}=fixture(),before=JSON.stringify(view),random=structuredClone(state.random);const result=await movementBattleEstimate(view,[ship.id],target.id);expect(result.status).toBe('estimate');if(result.status==='estimate'){expect(result.winPercent).toBeGreaterThan(50);expect(result.trials).toBeGreaterThanOrEqual(32);expect(result.trials).toBeLessThanOrEqual(96);expect(result.lowerPercent).toBeLessThanOrEqual(result.winPercent);expect(result.upperPercent).toBeGreaterThanOrEqual(result.winPercent);}expect(JSON.stringify(view)).toBe(before);expect(state.random).toEqual(random);});
 it('does not present a no-enemy sector as a guaranteed combat win',async()=>{const {view,ship,target}=fixture();view.ships=view.ships.filter(item=>item.owner!=='b');expect(await movementBattleEstimate(view,[ship.id],target.id)).toMatchObject({status:'peaceful'});});
 it('refuses to combine multiple opposing factions into one allied fleet',async()=>{const {view,ship,target}=fixture();view.ships.push({id:'ancient-extra',owner:'ancient',sectorId:target.id,type:'ancient',damage:0});expect(await movementBattleEstimate(view,[ship.id],target.id)).toMatchObject({status:'unavailable',reason:expect.stringMatching(/multiple factions/i)});});
 it('estimates neutral defenders but respects Draco coexistence',async()=>{const {view,ship}=fixture();const center=view.sectors.find(sector=>sector.tileId==='001')!;expect((await movementBattleEstimate(view,[ship.id],center.id)).status).toBe('estimate');const draco=createGame({seed:1,seats:[{id:'a',faction:'draco',controller:'human'},{id:'b',faction:'hydran',controller:'ai'}]});const own=draco.ships.find(item=>item.owner==='a')!,target=draco.sectors.find(sector=>sector.owner==='b')!;draco.ships=draco.ships.filter(item=>item.owner!=='b');draco.ships.push({id:'ancient',owner:'ancient',sectorId:target.id,type:'ancient',damage:0});expect(await movementBattleEstimate(getPlayerView(draco,'a'),[own.id],target.id)).toMatchObject({status:'peaceful'});});
 it('rejects unknown or enemy attacking ships and oversized previews',async()=>{const {view,ship,target}=fixture();expect((await movementBattleEstimate(view,['not-visible'],target.id)).status).toBe('unavailable');expect((await movementBattleEstimate(view,[view.ships.find(item=>item.owner==='b')!.id],target.id)).status).toBe('unavailable');for(let n=0;n<25;n++)view.ships.push({...ship,id:`extra-${n}`});expect(await movementBattleEstimate(view,view.ships.filter(item=>item.owner==='a').map(item=>item.id),target.id)).toMatchObject({status:'unavailable',reason:expect.stringMatching(/large/i)});});
 it('applies sector-owner defender advantage and includes existing friendly ships',async()=>{const {view,ship,target}=fixture();target.owner='a';view.ships.push({...ship,id:'existing-defender',sectorId:target.id});const result=await movementBattleEstimate(view,[ship.id],target.id);expect(result).toMatchObject({status:'estimate',defender:true,friendlyShips:2,enemyShips:1});});
 it('cancels while batches yield when the player changes selection',async()=>{const {view,ship,target}=fixture(),abort=new AbortController();const pending=movementBattleEstimate(view,[ship.id],target.id,abort.signal);abort.abort();expect(await pending).toMatchObject({status:'unavailable',reason:'Selection changed.'});});
 it('cancels superseded estimates without sampling or touching state',async()=>{const {view,ship,target}=fixture(),abort=new AbortController();abort.abort();expect(await movementBattleEstimate(view,[ship.id],target.id,abort.signal)).toMatchObject({status:'unavailable',reason:'Selection changed.'});});
});
