import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { processGameCommand } from '../../shared/eclipse/engine';
import { recoverHistoryCheckpoint } from '../../shared/eclipse/historyRecovery';
import { legalCommands } from '../../shared/eclipse/legal';
import { commitCommand, getPlayerView } from '../../shared/eclipse/protocol';
import { createGame } from '../../shared/eclipse/setup';
import type { GameState, JournalEntry } from '../../shared/eclipse/types';

interface ClosedEdgeHistory {
  anchor: GameState;
  entries: Pick<JournalEntry, 'actor' | 'request'>[];
  drawn: GameState;
}
function closedEdgeHistory(): ClosedEdgeHistory {
  return JSON.parse(readFileSync('src/__tests__/fixtures/guild_closed_edge_history.json', 'utf8'));
}

describe('historical Guild remote exploration recovery', () => {
  it('recovers a pre-fix closed-edge draw and discard without mutating its trusted history', () => {
    // Captured before the source-wormhole fix, rather than generated by current
    // legality: this draw was accepted even though no tile rotation could connect.
    const history = closedEdgeHistory();
    const initial = createGame({
      seed: 22, warpPortals: true, randomizeStartingPlayer: false, factionProfile: 'scifi-v1',
      seats: [
        { id: 'guild', faction: 'spacing-guild', controller: 'human' },
        { id: 'rival', faction: 'hydran', controller: 'human' },
      ],
    });
    expect(history.entries[0].request.command)
      .toEqual({ type: 'explore', position: { q: -1, r: -2 }, remote: true });
    expect(history.drawn.pendingDecision?.kind).toBe('exploration');
    if (history.drawn.pendingDecision?.kind !== 'exploration') throw new Error('Expected the captured remote draw.');
    expect(history.drawn.pendingDecision.placements).toEqual([]);
    expect(history.anchor.revision).toBe(2);
    const saved = structuredClone(history);
    expect(recoverHistoryCheckpoint({ anchor: history.anchor, entries: history.entries, targetRevision: 1 }))
      .toEqual({ ok: true, checkpoint: initial });
    expect(recoverHistoryCheckpoint({ anchor: history.anchor, entries: history.entries, targetRevision: 2 }))
      .toEqual({ ok: true, checkpoint: history.drawn });
    expect(history).toEqual(saved);
  });

  it('lets the current live processor discard an already saved closed-edge draw', () => {
    const history = closedEdgeHistory();
    const saved = structuredClone(history);
    const entry = history.entries[1];
    const discarded = commitCommand({ state: history.drawn, journal: [] }, entry.actor,
      entry.request, history.drawn, processGameCommand);
    expect(discarded.ok).toBe(true);
    if (!discarded.ok) throw new Error(discarded.error.message);
    expect(discarded.aggregate.state).toEqual(history.anchor);
    expect(history).toEqual(saved);
  });

  it('rejects a corrupted historical anchor even when legacy replay accepts its draw', () => {
    const history = closedEdgeHistory();
    history.anchor.seats[0].resources.money++;
    const saved = structuredClone(history);
    expect(recoverHistoryCheckpoint({ anchor: history.anchor, entries: history.entries, targetRevision: 2 }))
      .toEqual({ ok: false, reason: 'anchor-mismatch' });
    expect(history).toEqual(saved);
  });

  it('reconstructs a saved draw and discard with the legacy round marker intact', () => {
    const initial = createGame({
      seed: 22,
      warpPortals: true,
      randomizeStartingPlayer: false,
      factionProfile: 'scifi-v1',
      seats: [
        { id: 'guild', faction: 'spacing-guild', controller: 'human' },
        { id: 'rival', faction: 'hydran', controller: 'human' },
      ],
    });
    const remote = legalCommands(getPlayerView(initial, 'guild')!)
      .find(candidate => candidate.command.type === 'explore' && candidate.command.remote);
    expect(remote).toBeDefined();
    if (!remote) throw new Error('The initial Guild position must offer remote exploration.');
    const draw = commitCommand({ state: initial, journal: [] }, 'guild', {
      commandId: 'historical-guild-draw', expectedRevision: 0, command: remote.command,
    }, initial, processGameCommand);
    expect(draw.ok).toBe(true);
    if (!draw.ok) throw new Error(draw.error.message);
    const drawn = draw.aggregate.state;
    expect(drawn.seats[0].scifi?.remoteExploreRound).toBe(1);
    const decision = drawn.pendingDecision;
    expect(decision?.kind).toBe('exploration');
    if (decision?.kind !== 'exploration') throw new Error('The committed draw must await placement.');
    const discard = commitCommand({ state: drawn, journal: [] }, 'guild', {
      commandId: 'historical-guild-discard', expectedRevision: 1,
      command: { type: 'resolve', decisionId: decision.id, choice: { kind: 'exploration', tileId: null, rotation: 0 } },
    }, drawn, processGameCommand);
    expect(discard.ok).toBe(true);
    if (!discard.ok) throw new Error(discard.error.message);
    const anchor = structuredClone(discard.aggregate.state);
    // Historical snapshots persist this field even though it no longer limits exploration.
    expect(anchor.seats[0].scifi?.remoteExploreRound).toBe(1);
    const entries: JournalEntry[] = [draw.aggregate.journal[0], discard.aggregate.journal[0]];
    const saved = structuredClone({ anchor, entries });
    expect(recoverHistoryCheckpoint({ anchor, entries, targetRevision: 1 }))
      .toEqual({ ok: true, checkpoint: initial });
    expect(recoverHistoryCheckpoint({ anchor, entries, targetRevision: 2 }))
      .toEqual({ ok: true, checkpoint: drawn });
    expect({ anchor, entries }).toEqual(saved);
  });
});
