import {createRoot} from 'react-dom/client';
import './index.css';
import fixtures from './second-dawn-game/reviewFixtures.json';
import SecondDawnBoard from './second-dawn-game/SecondDawnBoard';
import {getPlayerView} from '../shared/eclipse/protocol';
import {legalCommands} from '../shared/eclipse/legal';
import type {GameState} from '../shared/eclipse/types';
const state=structuredClone(fixtures.midgame) as GameState;
state.seats[0].controller='human';
state.activeSeatId='p0';
const view=getPlayerView(state,'p0')!;
createRoot(document.getElementById('root')!).render(<SecondDawnBoard view={view} candidates={legalCommands(view)} connected busy={false} status="Local layout review" onSubmit={()=>{}} onMenu={()=>{}} initialSectorId={view.sectors.find(sector=>sector.owner==='p0')?.id}/>);
